-- Classic Era reagent definitions.

local _, L = ...
local RegisterExpansion = L.ReagentTracker and L.ReagentTracker.RegisterExpansion
if not RegisterExpansion then return end

RegisterExpansion({
	name = "Classic",
	labelKey = "rClassic",
	shortLabelKey = "rClassic",
	professions = {
		{
			id = "TITAN_RESENCHM_CL",
			professionKey = "enchanting",
			professionName = "Enchanting",
			icon = "Interface\\Icons\\Trade_engraving",
			items = {
				{ name = "Strange Dust", ids = { 10940 } },
				{ name = "Soul Dust", ids = { 11083 } },
				{ name = "Vision Dust", ids = { 11137 } },
				{ name = "Dream Dust", ids = { 11176 } },
				{ name = "Illusion Dust", ids = { 16204 } },
				{ name = "Lesser Magic Essence", ids = { 10938 } },
				{ name = "Greater Magic Essence", ids = { 10939 } },
				{ name = "Lesser Astral Essence", ids = { 10998 } },
				{ name = "Greater Astral Essence", ids = { 11082 } },
				{ name = "Lesser Mystic Essence", ids = { 11134 } },
				{ name = "Greater Mystic Essence", ids = { 11135 } },
				{ name = "Lesser Nether Essence", ids = { 11174 } },
				{ name = "Greater Nether Essence", ids = { 11175 } },
				{ name = "Lesser Eternal Essence", ids = { 16202 } },
				{ name = "Greater Eternal Essence", ids = { 16203 } },
				{ name = "Small Glimmering Shard", ids = { 10978 } },
				{ name = "Large Glimmering Shard", ids = { 11084 } },
				{ name = "Small Glowing Shard", ids = { 11138 } },
				{ name = "Large Glowing Shard", ids = { 11139 } },
				{ name = "Small Radiant Shard", ids = { 11177 } },
				{ name = "Large Radiant Shard", ids = { 11178 } },
				{ name = "Small Brilliant Shard", ids = { 14343 } },
				{ name = "Large Brilliant Shard", ids = { 14344 } },
				{ name = "Nexus Crystal", ids = { 20725 } },
			},
		},
		{
			id = "TITAN_RESFISHM_CL",
			professionKey = "fishing",
			professionName = "Fishing",
			icon = "Interface\\Icons\\Trade_fishing",
			items = {
				{ name = "Raw Brilliant Smallfish", ids = { 6291 } },
				{ name = "Raw Longjaw Mud Snapper", ids = { 6289 } },
				{ name = "Raw Slitherskin Mackerel", ids = { 6303 } },
				{ name = "Raw Rainbow Fin Albacore", ids = { 6361 } },
				{ name = "Raw Loch Frenzy", ids = { 6317 } },
				{ name = "Raw Bristle Whisker Catfish", ids = { 6308 } },
				{ name = "Raw Rockscale Cod", ids = { 6362 } },
				{ name = "Raw Mithril Head Trout", ids = { 8365 } },
				{ name = "Raw Spotted Yellowtail", ids = { 4603 } },
				{ name = "Raw Summer Bass", ids = { 13756 } },
				{ name = "Raw Nightfin Snapper", ids = { 13759 } },
				{ name = "Raw Sunscale Salmon", ids = { 13760 } },
				{ name = "Raw Glossy Mightfish", ids = { 13754 } },
				{ name = "Large Raw Mightfish", ids = { 13893 } },
				{ name = "Raw Whitescale Salmon", ids = { 13889 } },
				{ name = "Darkclaw Lobster", ids = { 13888 } },
				{ name = "Firefin Snapper", ids = { 6359 } },
				{ name = "Oily Blackmouth", ids = { 6358 } },
				{ name = "Stonescale Eel", ids = { 13422 } },
				{ name = "Winter Squid", ids = { 13755 } },
				{ name = "Deviate Fish", ids = { 6522 } },
			},
		},
		{
			id = "TITAN_RESHERBM_CL",
			professionKey = "herbalism",
			professionName = "Herbalism",
			icon = "Interface\\Icons\\Trade_herbalism",
			items = {
				{ name = "Peacebloom", ids = { 2447 } },
				{ name = "Silverleaf", ids = { 765 } },
				{ name = "Earthroot", ids = { 2449 } },
				{ name = "Mageroyal", ids = { 785 } },
				{ name = "Briarthorn", ids = { 2450 } },
				{ name = "Swiftthistle", ids = { 2452 } },
				{ name = "Bruiseweed", ids = { 2453 } },
				{ name = "Stranglekelp", ids = { 3820 } },
				{ name = "Wild Steelbloom", ids = { 3355 } },
				{ name = "Grave Moss", ids = { 3369 } },
				{ name = "Kingsblood", ids = { 3356 } },
				{ name = "Liferoot", ids = { 3357 } },
				{ name = "Fadeleaf", ids = { 3818 } },
				{ name = "Goldthorn", ids = { 3821 } },
				{ name = "Khadgar's Whisker", ids = { 3358 } },
				{ name = "Wintersbite", ids = { 3819 } },
				{ name = "Firebloom", ids = { 4625 } },
				{ name = "Purple Lotus", ids = { 8831 } },
				{ name = "Arthas' Tears", ids = { 8836 } },
				{ name = "Sungrass", ids = { 8838 } },
				{ name = "Blindweed", ids = { 8839 } },
				{ name = "Ghost Mushroom", ids = { 8845 } },
				{ name = "Gromsblood", ids = { 8846 } },
				{ name = "Golden Sansam", ids = { 13464 } },
				{ name = "Dreamfoil", ids = { 13463 } },
				{ name = "Mountain Silversage", ids = { 13465 } },
				{ name = "Plaguebloom", ids = { 13466 } },
				{ name = "Icecap", ids = { 13467 } },
				{ name = "Black Lotus", ids = { 13468 } },
			},
		},
		{
			id = "TITAN_RESMINIM_CL",
			professionKey = "mining",
			professionName = "Mining",
			icon = "Interface\\Icons\\Trade_mining",
			items = {
				{ name = "Copper Ore", ids = { 2770 } },
				{ name = "Tin Ore", ids = { 2771 } },
				{ name = "Silver Ore", ids = { 2775 } },
				{ name = "Iron Ore", ids = { 2772 } },
				{ name = "Gold Ore", ids = { 2776 } },
				{ name = "Mithril Ore", ids = { 3858 } },
				{ name = "Truesilver Ore", ids = { 7911 } },
				{ name = "Thorium Ore", ids = { 10620 } },
				{ name = "Dark Iron Ore", ids = { 11370 } },
				{ name = "Rough Stone", ids = { 2835 } },
				{ name = "Coarse Stone", ids = { 2836 } },
				{ name = "Heavy Stone", ids = { 2838 } },
				{ name = "Solid Stone", ids = { 7912 } },
				{ name = "Dense Stone", ids = { 12365 } },
			},
		},
		{
			id = "TITAN_RESSKINM_CL",
			professionKey = "skinning",
			professionName = "Skinning",
			icon = "Interface\\Icons\\Inv_misc_pelt_wolf_01",
			items = {
				{ name = "Ruined Leather Scraps", ids = { 2934 } },
				{ name = "Light Leather", ids = { 2318 } },
				{ name = "Medium Leather", ids = { 2319 } },
				{ name = "Heavy Leather", ids = { 4234 } },
				{ name = "Thick Leather", ids = { 4304 } },
				{ name = "Rugged Leather", ids = { 8170 } },
				{ name = "Light Hide", ids = { 783 } },
				{ name = "Medium Hide", ids = { 4232 } },
				{ name = "Heavy Hide", ids = { 4235 } },
				{ name = "Thick Hide", ids = { 8169 } },
				{ name = "Rugged Hide", ids = { 8171 } },
				{ name = "Green Dragonscale", ids = { 15412 } },
				{ name = "Red Dragonscale", ids = { 15414 } },
				{ name = "Blue Dragonscale", ids = { 15415 } },
				{ name = "Black Dragonscale", ids = { 15416 } },
			},
		},
		{
			id = "TITAN_RESTAILM_CL",
			professionKey = "tailoring",
			professionName = "Tailoring",
			icon = "Interface\\Icons\\Trade_tailoring",
			items = {
				{ name = "Linen Cloth", ids = { 2589 } },
				{ name = "Wool Cloth", ids = { 2592 } },
				{ name = "Silk Cloth", ids = { 4306 } },
				{ name = "Mageweave Cloth", ids = { 4338 } },
				{ name = "Runecloth", ids = { 14047 } },
				{ name = "Mooncloth", ids = { 14342 } },
			},
		},
	},
})
