-- The Burning Crusade reagent definitions.

local _, L = ...
local RegisterExpansion = L.ReagentTracker and L.ReagentTracker.RegisterExpansion
if not RegisterExpansion then return end

RegisterExpansion({
	name = "The Burning Crusade",
	labelKey = "rTBC",
	shortLabelKey = "rTBC",
	professions = {
		{
			id = "TITAN_RESCOOMM_TBC",
			professionKey = "cooking",
			professionName = "Cooking",
			icon = "Interface\\Icons\\Inv_misc_food_15.blp",
			items = {
				{ name = "Buzzard Meat", ids = { 27671 } },
				{ name = "Ravager Flesh", ids = { 27674 } },
				{ name = "Chunk o' Basilisk", ids = { 27677 } },
				{ name = "Clefthoof Meat", ids = { 27678 } },
				{ name = "Warped Flesh", ids = { 27681 } },
				{ name = "Talbuk Venison", ids = { 27682 } },
				{ name = "Raptor Ribs", ids = { 31670 } },
				{ name = "Serpent Flesh", ids = { 31671 } },
			},
		},
		{
			id = "TITAN_RESENCHM_TBC",
			professionKey = "enchanting",
			professionName = "Enchanting",
			icon = "Interface\\Icons\\Trade_engraving",
			items = {
				{ name = "Arcane Dust", ids = { 22445 } },
				{ name = "Greater Planar Essence", ids = { 22446 } },
				{ name = "Lesser Planar Essence", ids = { 22447 } },
				{ name = "Small Prismatic Shard", ids = { 22448 } },
				{ name = "Large Prismatic Shard", ids = { 22449 } },
				{ name = "Void Crystal", ids = { 22450 } },
			},
		},
		{
			id = "TITAN_RESFISHM_TBC",
			professionKey = "fishing",
			professionName = "Fishing",
			icon = "Interface\\Icons\\Trade_fishing",
			items = {
				{ name = "Barbed Gill Trout", ids = { 27422 } },
				{ name = "Spotted Feltail", ids = { 27425 } },
				{ name = "Zangarian Sporefish", ids = { 27429 } },
				{ name = "Figluster's Mudfish", ids = { 27435 } },
				{ name = "Icefin Bluefish", ids = { 27437 } },
				{ name = "Golden Darter", ids = { 27438 } },
				{ name = "Furious Crawdad", ids = { 27439 } },
				{ name = "Bloodfin Catfish", ids = { 33823 } },
				{ name = "Crescent-Tail Skullfish", ids = { 33824 } },
				{ name = "Mote of Water", ids = { 22578 } },
				{ name = "Primal Water", ids = { 21885 } },
			},
		},
		{
			id = "TITAN_RESHERBM_TBC",
			professionKey = "herbalism",
			professionName = "Herbalism",
			icon = "Interface\\Icons\\Trade_herbalism",
			items = {
				{ name = "Felweed", ids = { 22785 } },
				{ name = "Dreaming Glory", ids = { 22786 } },
				{ name = "Ragveil", ids = { 22787 } },
				{ name = "Flame Cap", ids = { 22788 } },
				{ name = "Terocone", ids = { 22789 } },
				{ name = "Ancient Lichen", ids = { 22790 } },
				{ name = "Netherbloom", ids = { 22791 } },
				{ name = "Nightmare Vine", ids = { 22792 } },
				{ name = "Mana Thistle", ids = { 22793 } },
				{ name = "Fel Lotus", ids = { 22794 } },
				{ name = "Nightmare Seed", ids = { 22797 } },
				{ name = "Mote of Life", ids = { 22575 } },
				{ name = "Primal Life", ids = { 21886 } },
				{ name = "Mote of Mana", ids = { 22576 } },
				{ name = "Primal Mana", ids = { 22457 } },
			},
		},
		{
			id = "TITAN_RESJEWCM_TBC",
			professionKey = "jewelcrafting",
			professionName = "Jewelcrafting",
			icon = "Interface\\Icons\\Inv_misc_gem_02.blp",
			items = {
				{ name = "Blood Garnet", ids = { 23077 } },
				{ name = "Flame Spessarite", ids = { 21929 } },
				{ name = "Deep Peridot", ids = { 23079 } },
				{ name = "Shadow Draenite", ids = { 23107 } },
				{ name = "Golden Draenite", ids = { 23112 } },
				{ name = "Azure Moonstone", ids = { 23117 } },
				{ name = "Living Ruby", ids = { 23436 } },
				{ name = "Talasite", ids = { 23437 } },
				{ name = "Star of Elune", ids = { 23438 } },
				{ name = "Noble Topaz", ids = { 23439 } },
				{ name = "Dawnstone", ids = { 23440 } },
				{ name = "Nightseye", ids = { 23441 } },
				{ name = "Earthstorm Diamond", ids = { 25867 } },
				{ name = "Skyfire Diamond", ids = { 25868 } },
				{ name = "Crimson Spinel", ids = { 32227 } },
				{ name = "Empyrean Sapphire", ids = { 32228 } },
				{ name = "Lionseye", ids = { 32229 } },
				{ name = "Shadowsong Amethyst", ids = { 32230 } },
				{ name = "Pyrestone", ids = { 32231 } },
				{ name = "Seaspray Emerald", ids = { 32249 } },
			},
		},
		{
			id = "TITAN_RESMINIM_TBC",
			professionKey = "mining",
			professionName = "Mining",
			icon = "Interface\\Icons\\Trade_mining",
			items = {
				{ name = "Fel Iron Ore", ids = { 23424 } },
				{ name = "Adamantite Ore", ids = { 23425 } },
				{ name = "Khorium Ore", ids = { 23426 } },
				{ name = "Eternium Ore", ids = { 23427 } },
				{ name = "Mote of Fire", ids = { 22574 } },
				{ name = "Primal Fire", ids = { 21884 } },
				{ name = "Mote of Earth", ids = { 22573 } },
				{ name = "Primal Earth", ids = { 22452 } },
			},
		},
		{
			id = "TITAN_RESSKINM_TBC",
			professionKey = "skinning",
			professionName = "Skinning",
			icon = "Interface\\Icons\\Inv_misc_pelt_wolf_01",
			items = {
				{ name = "Knothide Leather Scraps", ids = { 25649 } },
				{ name = "Knothide Leather", ids = { 21887 } },
				{ name = "Heavy Knothide Leather", ids = { 23793 } },
				{ name = "Fel Hide", ids = { 25707 } },
				{ name = "Crystal Infused Leather", ids = { 25699 } },
				{ name = "Thick Clefthoof Leather", ids = { 25708 } },
				{ name = "Fel Scales", ids = { 25700 } },
				{ name = "Wind Scales", ids = { 29547 } },
				{ name = "Cobra Scales", ids = { 29539 } },
				{ name = "Nether Dragonscales", ids = { 29548 } },
			},
		},
		{
			id = "TITAN_RESTAILM_TBC",
			professionKey = "tailoring",
			professionName = "Tailoring",
			icon = "Interface\\Icons\\Trade_tailoring",
			items = {
				{ name = "Netherweave Cloth", ids = { 21877 } },
				{ name = "Bolt of Netherweave", ids = { 21840 } },
				{ name = "Bolt of Imbued Netherweave", ids = { 21842 } },
				{ name = "Bolt of Soulcloth", ids = { 21844 } },
				{ name = "Primal Mooncloth", ids = { 21845 } },
				{ name = "Spellcloth", ids = { 24271 } },
				{ name = "Shadowcloth", ids = { 24272 } },
			},
		},
	},
})
